from telegram_bot.handlers.user.commands_handlers import CommandHandler
from telegram_bot.handlers.other import OtherHandler
from telegram_bot.handlers.user.operation_handlers import OperationHandler
from telegram_bot.handlers.user.setting_handlers import SettingHandler
